# Site settings
languageCode = "es-us"
title = "Vektor Costa Rica"

[params]

    name = "Vektor Costa Rica"
    description = "Empresa de consultoria de salud ocupacional"

        # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "cicelcup@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        logo = "vektor-logo-white.jpg"


    [params.header]
        image = ""
        name = "Vektor Costa Rica"
        subtitle = "Capacitaciones - Certificaciones - Validación de Requerimientos"


    [params.portfolio]
        title = "Cursos"

        [params.portfolio.modal]
            informacion = "Contenido del curso"
            buttontext = "Volver"

    [params.about]
        title = "Nosotros"
        left = "Somos un equipo de trabajo con más de 10 años de experiencia en proyectos y capacitaciones en seguridad, ambiente e higiene ocupacional en el sector industrial, construcción, agropecuario, comercio y dispositivos médicos"
        right = "Visión: Lograr ser líderes en nuestra área para el año 2020, garantizando siempre la calidad y profesionalismo de nuestros servicios."
        center = "Misión: Nuestra misión es alcanzar su visión."

    [params.services]
        title = "Servicios"
        A1 = "Vektor ha desarrollado un sistema de capacitación y entrenamiento personalizado por empresa; en el cual nuestro personal investiga, adopta y confecciona capacitaciones basadas en sus políticas internas de EHS, calidad e inocuidad del producto. Esto con la finalidad de que sus empresas subcontratistas sigan los lineamientos de seguridad."
        B1 = "Los conocimientos adquiridos son respaldados con un amplio material visual, auditivo y bibliográfico que permite al participante profundizar en el conocimiento."
        B2 = "Somos el filtro en cuanto a documentación legal (INS, CCSS) que su empresa debe solicitar a los subcontratistas."        
        B3 = "Se proporciona al participante un plan de acciones seguras diseñado durante la capacitación, que pondrá en práctica de manera inmediata en su área de trabajo."
        B4 = "Formamos personas competentes en las tareas criticas aplicables a su empresa."
    
    [params.team]
        title = "Nuestro equipo"

        [params.team.team1]
            name = "Ing. Diego Brenes"
            title = "Gestor de Proyecto"
            email = "dbrenes@vektorcr.com"
            tel = "Tel: 8859-8335"

        [params.team.team2]
            name = "Ing. Carlos Brenes"
            title = "Gestor de Proyecto"
            email = "cbrenes@vektorcr.com"
            tel = "Tel: 7208-3856"

        [params.team.team3]
            name = "Katherine Pineda"
            title = "Oficina administrativa"
            email = "kpiedra@vektorcr.com"
            tel = "Tel: 7112-9590 / 4001-6915"    
    
    [params.contact]
        title = "Contacto"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Nombre"
            error = "Por favor introduzca su nombre"

        [params.contact.form.email]
            text = "Correo electrónico"
            error = "Por favor introduzca su correo electrónico"

        [params.contact.form.phone]
            text = "Teléfono"
            error = "Por favor introduzca su número teléfonico"

        [params.contact.form.message]
            text = "Mensaje"
            error = "Por favor introduzca un mensaje"

        [params.contact.form.button]
            text = "Enviar"


    [params.footer]
        copyright = "©Todos los derechos reservados"

        contactemail = "info@vektorcr.com"
        contactphone = "Tel: 4001-6915 / 7112-9590"

        [params.footer.location]
            title = "Vektor Costa Rica"
            mensaje = ["Juntos hacía el éxito"]

        [params.footer.social]
            title = "Redes Sociales"
            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link = "//www.facebook.com/Vektor-Safety-2042099979401870/"

            [[params.footer.social.networks]]
                icon = "fa-youtube"
                link=  "https://www.youtube.com/channel/UC0UBddXUX5tuTlFPVsdwPlg"


        [params.footer.certification]
            title = ""
            image = "cfiaBlanco1.jpg"
            text = "Inscripción: CC-08948"
